include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  exclude:
    # Generated files
    - lib/generated_plugin_registrant.dart
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
